name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add the server to known hosts
      run: |
        ssh-keyscan -H ec2-3-89-68-4.compute-1.amazonaws.com >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ec2-user@ec2-3-89-68-4.compute-1.amazonaws.com "cd mcqgen && git pull origin main && source venv/bin/activate && pip install -r requirements.txt && streamlit run StreamlitAPP.py --server.port 8501 --server.address 0.0.0.0"

